### ISSUE TITLE
创世之初，会遇到各种问题

### ISSUE THREAD

**Issue by xunyixiangchao** [Qihoo360/ArgusAPM#20]
1：编译报错
程序有多library,有分包
ABORT
org.aspectj.weaver.BCException: Whilst processing type 'Lcom/hyphenate/chat/EMCallManager$EMVideoCallHelper;' - cannot cast the outer type to a reference type.  Signature=Lcom/hyphenate/chat/EMCallManager; toString()=com.hyphenate.chat.EMCallManager class=EMCallManager
when processing type mungers 
when weaving 
when batch building with classpath: C:\Program Files\Java\jdk1.8.0_141\jre\lib\ext\access-bridge-64.jar;C:\Program Files\Java\jdk1.8.0_141\jre\lib\ext\cldrdata.jar;C:\Program Files\Java\jdk1.8.0_141\jre\lib\ext\dnsns.jar;C:\Program Files\Java\jdk1.8.0_141\jre\lib\ext\jaccess.jar;C:\Program Files\Java\jdk1.8.0_141\jre\lib\ext\jfxrt.jar;C:\Program Files\Java\jdk1.8.0_141\jre\lib\ext\localedata.jar;C:\Program Files\Java\jdk1.8.0_141\jre\lib\ext\nashorn.jar;C:\Program Files\Java\jdk1.8.0_141\jre\lib\ext\sunec.jar;C:\Program Files\Java\jdk1.8.0_141\jre\lib\ext\sunjce_provider.jar;C:\Program Files\Java\jdk1.8.0_141\jre\lib\ext\sunmscapi.jar;C:\Program Files\Java\jdk1.8.0_141\jre\lib\ext\sunpkcs11.jar;C:\Program Files\Java\jdk1.8.0_141\jre\lib\ext\zipfs.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\trunk\app\libs\alipaySdk-20160516.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\trunk\app\libs\BestpaySDK-V4.0.2.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\trunk\app\libs\com.bonree.agent.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\trunk\app\libs\maa_sdk_android.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\trunk\app\libs\passguard.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\trunk\app\libs\pushservice-4.6.2.39.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\trunk\app\libs\UPPayAssistEx.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\trunk\app\libs\UPPayPluginExPro.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\trunk\app\libs\Vuforia.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\trunk\app\build\intermediates\exploded-aar\com.github.chrisbanes.photoview\library\1.2.4\jars\classes.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\trunk\app\build\intermediates\exploded-aar\com.scwang.smartrefresh\SmartRefreshLayout\1.0.4-4\jars\classes.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\trunk\app\build\intermediates\exploded-aar\com.android.support\support-core-ui\24.2.1\jars\libs\internal_impl-24.2.1.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\trunk\app\build\intermediates\exploded-aar\com.android.support\cardview-v7\25.1.0\jars\classes.jar;C:\Users\Administrator\.gradle\wrapper\dists\gradle-4.1-all\caches\modules-2\files-2.1\com.github.bumptech.glide\glide\3.7.0\9e9eeaf9948ee4d6c3ab354e8dc14368f16994a4\glide-3.7.0.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\trunk\app\build\intermediates\exploded-aar\com.facebook.fresco\webpsupport\0.13.0\jars\classes.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\trunk\app\build\intermediates\exploded-aar\com.android.support\recyclerview-v7\24.2.1\jars\classes.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\trunk\app\build\intermediates\exploded-aar\com.android.support\support-compat\25.3.0\jars\classes.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\trunk\app\build\intermediates\exploded-aar\com.android.support\support-fragment\24.2.1\jars\classes.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\trunk\app\build\intermediates\exploded-aar\com.google.firebase\firebase-common\9.8.0\jars\classes.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\trunk\app\build\intermediates\exploded-aar\com.dalong\refreshlayout\1.0.3\jars\classes.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\trunk\app\build\intermediates\exploded-aar\com.czp.arcProgressBar\ArcProgressBar\1.0.1\jars\classes.jar;C:\Users\Administrator\.gradle\wrapper\dists\gradle-4.1-all\caches\modules-2\files-2.1\com.squareup.okhttp3\okhttp\3.7.0\6edbebdd8868708db718d15c09c4b28037fd487e\okhttp-3.7.0.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\trunk\app\build\intermediates\exploded-aar\com.google.android.gms\play-services-tasks\9.8.0\jars\classes.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\trunk\app\build\intermediates\exploded-aar\me.leolin\ShortcutBadger\1.1.19\jars\classes.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\trunk\app\build\intermediates\exploded-aar\com.kyleduo.switchbutton\library\1.4.0\jars\classes.jar;C:\Users\Administrator\.gradle\wrapper\dists\gradle-4.1-all\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-stdlib-jre7\1.1.3-2\3fe54c7558c903868351ac79b792d152bca958f2\kotlin-stdlib-jre7-1.1.3-2.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\trunk\app\build\intermediates\exploded-aar\com.github.hackware1993\MagicIndicator\1.5.0\jars\classes.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\trunk\app\build\intermediates\exploded-aar\com.qihoo360.argusapm\argus-apm-okhttp\2.0.1.1007\jars\classes.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\trunk\app\build\intermediates\exploded-aar\com.facebook.fresco\animated-webp\0.13.0\jars\classes.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\trunk\app\build\intermediates\exploded-aar\com.r0adkll\slidableactivity\2.0.5\jars\classes.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\trunk\app\build\intermediates\exploded-aar\com.facebook.fresco\animated-base\0.13.0\jars\classes.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\trunk\app\build\intermediates\exploded-aar\com.facebook.fresco\imagepipeline\0.13.0\jars\classes.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\trunk\app\build\intermediates\exploded-aar\com.android.support\multidex\1.0.1\jars\classes.jar;C:\Users\Administrator\.gradle\wrapper\dists\gradle-4.1-all\caches\modules-2\files-2.1\com.google.zxing\core\3.3.1\bd5bb06f4ae0fef8e67044131272905eb8895230\core-3.3.1.jar;C:\Users\Administrator\.gradle\wrapper\dists\gradle-4.1-all\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-stdlib\1.1.3-2\9b44c139a4ec57031e0c84ba0e49ba16df6d801c\kotlin-stdlib-1.1.3-2.jar;C:\Users\Administrator\.gradle\wrapper\dists\gradle-4.1-all\caches\modules-2\files-2.1\com.squareup.leakcanary\leakcanary-watcher\1.5.4\5e3dadce30fd748563219945d867a2e96f287931\leakcanary-watcher-1.5.4.jar;C:\Users\Administrator\.gradle\wrapper\dists\gradle-4.1-all\caches\modules-2\files-2.1\org.aspectj\aspectjrt\1.8.10\1a14fe9e912f6e8bdbb5429b78b4090d8b47bc1\aspectjrt-1.8.10.jar;D:\sdk\extras\android\m2repository\com\android\support\support-annotations\25.3.0\support-annotations-25.3.0.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\trunk\app\build\intermediates\exploded-aar\com.tencent.bugly\crashreport\2.6.6.1\jars\classes.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\trunk\app\build\intermediates\exploded-aar\com.github.michaelye.easydialog\easydialog\1.4\jars\classes.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\trunk\app\build\intermediates\exploded-aar\com.sensorsdata.analytics.android\SensorsAnalyticsSDK-Runtime\1.0.2\jars\classes.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\trunk\app\build\intermediates\exploded-aar\com.scwang.smartrefresh\SmartRefreshHeader\1.0.4-4\jars\classes.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\trunk\app\build\intermediates\exploded-aar\com.android.support\design\24.0.0\jars\classes.jar;C:\Users\Administrator\.gradle\wrapper\dists\gradle-4.1-all\caches\modules-2\files-2.1\com.squareup.haha\haha\2.0.3\640a438d2d415c056ca6a673ac26b183b044e160\haha-2.0.3.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\trunk\app\build\intermediates\exploded-aar\com.android.support\support-vector-drawable\24.2.1\jars\classes.jar;C:\Users\Administrator\.gradle\wrapper\dists\gradle-4.1-all\caches\modules-2\files-2.1\com.squareup.okio\okio\1.12.0\3742beff8024d0a0073d284b7c5e4cbf73d99b25\okio-1.12.0.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\trunk\app\build\intermediates\exploded-aar\com.squareup.leakcanary\leakcanary-android\1.5.4\jars\classes.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\trunk\app\build\intermediates\exploded-aar\com.ogaclejapan.smarttablayout\utils-v4\1.6.1\jars\classes.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\trunk\app\build\intermediates\exploded-aar\com.baoyz.swipemenulistview\library\1.3.0\jars\classes.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\trunk\app\build\intermediates\exploded-aar\com.google.android.gms\play-services-basement\9.8.0\jars\classes.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\trunk\app\build\intermediates\exploded-aar\cn.bingoogolapple\bga-refreshlayout\1.1.7\jars\classes.jar;C:\Users\Administrator\.gradle\wrapper\dists\gradle-4.1-all\caches\modules-2\files-2.1\com.jakewharton\butterknife-annotations\8.8.1\bc373fb6bc7bca3035041b924f158fd2b946ee8d\butterknife-annotations-8.8.1.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\trunk\app\build\intermediates\exploded-aar\com.sensorsdata.analytics.android\SensorsAnalyticsSDK\1.10.5\jars\classes.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\trunk\app\build\intermediates\exploded-aar\com.github.ctiao\DanmakuFlameMaster\0.4.4\jars\classes.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\trunk\app\build\intermediates\exploded-aar\it.sephiroth.android.library.horizontallistview\hlistview\1.3.1\jars\classes.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\trunk\app\build\intermediates\exploded-aar\cn.qqtheme.framework\Common\1.5.5\jars\classes.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\trunk\app\build\intermediates\exploded-aar\com.liulishuo.filedownloader\library\1.6.2\jars\classes.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\trunk\app\build\intermediates\exploded-aar\com.android.support\support-core-utils\24.2.1\jars\libs\internal_impl-24.2.1.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\trunk\app\build\intermediates\exploded-aar\com.jakewharton\butterknife\8.8.1\jars\classes.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\trunk\app\build\intermediates\exploded-aar\com.hyman\flowlayout-lib\1.1.2\jars\classes.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\trunk\app\build\intermediates\exploded-aar\com.facebook.fresco\fresco\0.13.0\jars\classes.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\trunk\app\build\intermediates\exploded-aar\com.android.support\animated-vector-drawable\24.2.1\jars\classes.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\trunk\app\build\intermediates\exploded-aar\com.android.support\support-core-ui\24.2.1\jars\classes.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\trunk\app\build\intermediates\exploded-aar\org.xutils\xutils\3.3.42\jars\classes.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\trunk\app\build\intermediates\exploded-aar\com.ogaclejapan.smarttablayout\library\1.6.1\jars\classes.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\trunk\app\build\intermediates\exploded-aar\com.facebook.fresco\fbcore\0.13.0\jars\classes.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\trunk\app\build\intermediates\exploded-aar\com.android.support\support-v4\24.2.1\jars\classes.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\trunk\app\build\intermediates\exploded-aar\com.squareup.leakcanary\leakcanary-analyzer\1.5.4\jars\classes.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\trunk\app\build\intermediates\exploded-aar\com.google.android.gms\play-services-appindexing\9.8.0\jars\classes.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\trunk\app\build\intermediates\exploded-aar\com.facebook.fresco\drawee\0.13.0\jars\classes.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\trunk\app\build\intermediates\exploded-aar\com.android.support\appcompat-v7\24.2.1\jars\classes.jar;C:\Users\Administrator\.gradle\wrapper\dists\gradle-4.1-all\caches\modules-2\files-2.1\org.jetbrains\annotations\13.0\919f0dfe192fb4e063e7dacadee7f8bb9a2672a9\annotations-13.0.jar;C:\Users\Administrator\.gradle\wrapper\dists\gradle-4.1-all\caches\modules-2\files-2.1\org.greenrobot\eventbus\3.0.0\ddd99896e9569eaababbe81b35d80e1b91c4ad85\eventbus-3.0.0.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\trunk\app\build\intermediates\exploded-aar\com.android.support\support-media-compat\24.2.1\jars\classes.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\trunk\app\build\intermediates\exploded-aar\in.srain.cube\ultra-ptr\1.0.11\jars\classes.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\trunk\app\build\intermediates\exploded-aar\com.android.support\support-core-utils\24.2.1\jars\classes.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\trunk\app\build\intermediates\exploded-aar\com.google.android.gms\play-services-base\9.8.0\jars\classes.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\trunk\app\build\intermediates\exploded-aar\com.tencent.bugly\nativecrashreport\3.3.1\jars\classes.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\trunk\app\build\intermediates\exploded-aar\com.bigkoo\convenientbanner\2.0.5\jars\classes.jar;C:\Users\Administrator\.gradle\wrapper\dists\gradle-4.1-all\caches\modules-2\files-2.1\org.jetbrains.kotlin\kotlin-reflect\1.1.3-2\2104f139db2a2d230c529b004c34a0993c4c2f19\kotlin-reflect-1.1.3-2.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\trunk\app\build\intermediates\exploded-aar\com.github.hotchemi\permissionsdispatcher\3.0.1\jars\classes.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\trunk\app\build\intermediates\exploded-aar\com.qihoo360.argusapm\argus-apm-aop\2.0.1.1007\jars\classes.jar;C:\Users\Administrator\.gradle\wrapper\dists\gradle-4.1-all\caches\modules-2\files-2.1\com.squareup.picasso\picasso\2.5.2\7446d06ec8d4f7ffcc53f1da37c95f200dcb9387\picasso-2.5.2.jar;C:\Users\Administrator\.gradle\wrapper\dists\gradle-4.1-all\caches\modules-2\files-2.1\com.parse.bolts\bolts-tasks\1.4.0\d85884acf6810a3bbbecb587f239005cbc846dc4\bolts-tasks-1.4.0.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\trunk\app\build\intermediates\exploded-aar\jp.wasabeef\glide-transformations\1.2.1\jars\classes.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\trunk\app\build\intermediates\exploded-aar\com.qihoo360.argusapm\argus-apm-main\2.0.1.1007\jars\classes.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\trunk\app\build\intermediates\exploded-aar\cn.qqtheme.framework\WheelPicker\1.5.5\jars\classes.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\trunk\app\build\intermediates\exploded-aar\com.android.support\support-media-compat\24.2.1\jars\libs\internal_impl-24.2.1.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\trunk\app\build\intermediates\exploded-aar\com.facebook.fresco\imagepipeline-base\0.13.0\jars\classes.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\trunk\app\build\intermediates\exploded-aar\com.android.support\support-fragment\24.2.1\jars\libs\internal_impl-24.2.1.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\Library\lib-o2o\build\intermediates\bundles\default\classes.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\Library\lib-rangedatepicker\build\intermediates\bundles\default\classes.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\Library\lib-education\build\intermediates\bundles\default\classes.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\trunk\lib-quanzi\build\intermediates\bundles\default\classes.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\Library\lib-im\build\intermediates\bundles\default\classes.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\Library\le_library\build\intermediates\bundles\default\classes.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\Library\lib-new_sdk_library\build\intermediates\bundles\default\classes.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\Library\lib-xiaoneng\build\intermediates\bundles\default\classes.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\Library\ui-xiaonengChat\build\intermediates\bundles\default\classes.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\Library\ui-ease-release_3.1.5\build\intermediates\bundles\default\classes.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\Library\lib-busmodule\build\intermediates\bundles\default\classes.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\Library\lib-core\build\intermediates\bundles\default\classes.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\Library\lib-education\build\intermediates\bundles\default\libs\liteavsdk.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\trunk\lib-quanzi\build\intermediates\bundles\default\libs\android-support-v8-renderscript.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\trunk\lib-quanzi\build\intermediates\bundles\default\libs\gpuimage.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\trunk\lib-quanzi\build\intermediates\bundles\default\libs\touch_image.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\Library\le_library\build\intermediates\bundles\default\libs\aliyun-oss-sdk-android-2.3.0.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\Library\le_library\build\intermediates\bundles\default\libs\CILPaySDK.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\Library\le_library\build\intermediates\bundles\default\libs\GDTActionSDK.min.1.4.2.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\Library\le_library\build\intermediates\bundles\default\libs\ixintui_pushsdk_v1.9.5.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\Library\le_library\build\intermediates\bundles\default\libs\libammsdk.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\Library\le_library\build\intermediates\bundles\default\libs\SaaS_AppAnalytics_Android_SDK_V4.0.13.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\Library\le_library\build\intermediates\bundles\default\libs\testin-ab-v4.1.5.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\Library\le_library\build\intermediates\bundles\default\libs\WXModule.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\Library\lib-new_sdk_library\build\intermediates\bundles\default\libs\open_sdk_r5788_lite.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\Library\lib-new_sdk_library\build\intermediates\bundles\default\libs\SocialSDK_QQ_Simplify.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\Library\lib-new_sdk_library\build\intermediates\bundles\default\libs\SocialSDK_Sina_Simplify.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\Library\lib-new_sdk_library\build\intermediates\bundles\default\libs\SocialSDK_sms.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\Library\lib-new_sdk_library\build\intermediates\bundles\default\libs\SocialSDK_WeChat_Simplify.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\Library\lib-new_sdk_library\build\intermediates\bundles\default\libs\SocialSDK_whatsapp.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\Library\lib-new_sdk_library\build\intermediates\bundles\default\libs\umeng_shareboard_widget.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\Library\lib-new_sdk_library\build\intermediates\bundles\default\libs\umeng_social_api.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\Library\lib-new_sdk_library\build\intermediates\bundles\default\libs\umeng_social_net.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\Library\lib-new_sdk_library\build\intermediates\bundles\default\libs\umeng_social_shareboard.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\Library\lib-new_sdk_library\build\intermediates\bundles\default\libs\umeng_social_shareview.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\Library\lib-new_sdk_library\build\intermediates\bundles\default\libs\umeng_social_tool.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\Library\lib-new_sdk_library\build\intermediates\bundles\default\libs\volley.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\Library\ui-xiaonengChat\build\intermediates\bundles\default\libs\xiaoneng-mqtt.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\Library\ui-xiaonengChat\build\intermediates\bundles\default\libs\xiaonengchatcore.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\Library\ui-xiaonengChat\build\intermediates\bundles\default\libs\xiaonengchatui.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\Library\ui-xiaonengChat\build\intermediates\bundles\default\libs\xiaonengnetwork.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\Library\ui-xiaonengChat\build\intermediates\bundles\default\libs\xiaonengutil.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\Library\ui-xiaonengChat\build\intermediates\bundles\default\libs\xiaonengv4.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\Library\ui-xiaonengChat\build\intermediates\bundles\default\libs\xiaonengxpush.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\Library\ui-ease-release_3.1.5\build\intermediates\bundles\default\libs\BaiduLBS_Android.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\Library\ui-ease-release_3.1.5\build\intermediates\bundles\default\libs\hyphenatechat_3.1.5.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\Library\lib-core\build\intermediates\bundles\default\libs\android-async-http-1.4.3.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\Library\lib-core\build\intermediates\bundles\default\libs\gson-2.2.2.jar;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\trunk\app\build\intermediates\argus_apm_ajx\longNameDebug\include_dir;D:\LeyouGitWorkspace\leyou-shop-18118\leyou-app-shop\trunk\app\build\intermediates\argus_apm_ajx\longNameDebug\exclude_dir;

	at org.aspectj.weaver.AbstractReferenceTypeDelegate.getFormalTypeParametersFromOuterClass(AbstractReferenceTypeDelegate.java:113)
	at org.aspectj.weaver.AbstractReferenceTypeDelegate.getFormalTypeParametersFromOuterClass(AbstractReferenceTypeDelegate.java:122)
	at org.aspectj.weaver.bcel.BcelObjectType.ensureGenericSignatureUnpacked(BcelObjectType.java:775)
	at org.aspectj.weaver.bcel.BcelObjectType.getSuperclass(BcelObjectType.java:231)
	at org.aspectj.weaver.ReferenceType.getSuperclass(ReferenceType.java:987)
	at org.aspectj.weaver.bcel.BcelWeaver.weaveParentsFor(BcelWeaver.java:1304)
	at org.aspectj.weaver.bcel.BcelWeaver.weave(BcelWeaver.java:1123)
	at org.aspectj.ajdt.internal.compiler.AjPipeliningCompilerAdapter.weaveQueuedEntries(AjPipeliningCompilerAdapter.java:514)
	at org.aspectj.ajdt.internal.compiler.AjPipeliningCompilerAdapter.afterCompiling(AjPipeliningCompilerAdapter.java:375)
	at org.aspectj.ajdt.internal.compiler.CompilerAdapter.ajc$afterReturning$org_aspectj_ajdt_internal_compiler_CompilerAdapter$2$f9cc9ca0(CompilerAdapter.java:69)
	at org.aspectj.org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:471)
	at org.aspectj.ajdt.internal.core.builder.AjBuildManager.performCompilation(AjBuildManager.java:1051)
	at org.aspectj.ajdt.internal.core.builder.AjBuildManager.performBuild(AjBuildManager.java:274)
	at org.aspectj.ajdt.internal.core.builder.AjBuildManager.batchBuild(AjBuildManager.java:187)
	at org.aspectj.ajdt.ajc.AjdtCommand.doCommand(AjdtCommand.java:112)
	at org.aspectj.ajdt.ajc.AjdtCommand.runCommand(AjdtCommand.java:60)
	at org.aspectj.tools.ajc.Main.run(Main.java:371)
	at com.argusapm.gradle.internal.ajc.AjcWeaver.call(AjcWeaver.kt:76)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

                  Argus-Apm [longNameDebug] end...                 
--------------------------------------------------------------------
:app:transformClassesWithArgus_apm_ajxForLongNameDebug spend 40249ms
AGPBI: {"kind":"error","text":"Uncaught translation error: com.android.dx.cf.code.SimException: local variable type mismatch: attempt to set or access a value of type int using a local variable of type android.content.Intent. This is symptomatic of .class transformation tools that ignore local variable information.","sources":[{}]}
AGPBI: {"kind":"error","text":"Uncaught translation error: com.android.dx.cf.code.SimException: local variable type mismatch: attempt to set or access a value of type int using a local variable of type java.lang.String. This is symptomatic of .class transformation tools that ignore local variable information.","sources":[{}]}
AGPBI: {"kind":"error","text":"2 errors; aborting","sources":[{}]}
:app:transformClassesWithDexForLongNameDebug FAILED
:app:transformClassesWithDexForLongNameDebug spend 1958ms

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithDexForLongNameDebug'.
> com.android.build.api.transform.TransformException: java.lang.RuntimeException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: Return code 1 for dex process

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 3m 14s

**Comment by xunyixiangchao** [comment]
使用argusapm.gradle后，
在Argus-Apm [longNameDebug] end...     
结束后报错，程序本身有MultiDex
加入argus后报这错
:app:transformClassesWithArgus_apm_ajxForLongNameDebug spend 41703ms
AGPBI: {"kind":"error","text":"Uncaught translation error: com.android.dx.cf.code.SimException: local variable type mismatch: attempt to set or access a value of type int using a local variable of type android.content.Intent. This is symptomatic of .class transformation tools that ignore local variable information.","sources":[{}]}
AGPBI: {"kind":"error","text":"Uncaught translation error: com.android.dx.cf.code.SimException: local variable type mismatch: attempt to set or access a value of type int using a local variable of type java.lang.String. This is symptomatic of .class transformation tools that ignore local variable information.","sources":[{}]}
AGPBI: {"kind":"error","text":"2 errors; aborting","sources":[{}]}
:app:transformClassesWithDexForLongNameDebug FAILED
:app:transformClassesWithDexForLongNameDebug spend 6964ms

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithDexForLongNameDebug'.
> com.android.build.api.transform.TransformException: java.lang.RuntimeException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: Return code 1 for dex process

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4m 16s
