### ISSUE TITLE
APP启动后闪退

### ISSUE THREAD

**Issue by cuzhu** [Qihoo360/ArgusAPM#26]
2019-01-03 14:36:51.268 22422-22422/com.julive.assistant E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.julive.assistant, PID: 22422
    java.lang.RuntimeException: Unable to instantiate application com.julive.assistant.app.JuliveAssistantApp: java.lang.ClassNotFoundException: Didn't find class "com.julive.assistant.app.JuliveAssistantApp" on path: DexPathList[[zip file "/data/app/com.julive.assistant-2/base.apk"],nativeLibraryDirectories=[/data/app/com.julive.assistant-2/lib/arm, /data/app/com.julive.assistant-2/base.apk!/lib/armeabi, /system/lib, /vendor/lib, /system/vendor/lib, /product/lib]]
        at android.app.LoadedApk.makeApplication(LoadedApk.java:855)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5732)
        at android.app.ActivityThread.-wrap2(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1648)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:156)
        at android.app.ActivityThread.main(ActivityThread.java:6623)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.julive.assistant.app.JuliveAssistantApp" on path: DexPathList[[zip file "/data/app/com.julive.assistant-2/base.apk"],nativeLibraryDirectories=[/data/app/com.julive.assistant-2/lib/arm, /data/app/com.julive.assistant-2/base.apk!/lib/armeabi, /system/lib, /vendor/lib, /system/vendor/lib, /product/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.Instrumentation.newApplication(Instrumentation.java:995)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:849)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5732) 
        at android.app.ActivityThread.-wrap2(ActivityThread.java) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1648) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:156) 
        at android.app.ActivityThread.main(ActivityThread.java:6623) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832) 
2019-01-03 14:36:51.277 696-1120/? E/logserver: imonitor_add_dynamic_path, path:/data/system/dropbox/data_app_crash@1546497411275.txt
2019-01-03 14:36:51.281 1607-3708/? E/ReportTools: This is not beta user build

**Comment by cuzhu** [comment]
classpath 'com.android.tools.build:gradle:3.2.1'

**Comment by cuzhu** [comment]
使用添加依赖的方式集成不再闪退，见常见问题FAQ
