### ISSUE TITLE
集成后，请求网络接口报错

### ISSUE THREAD

**Issue by cuzhu** [Qihoo360/ArgusAPM#27]
2019-01-03 17:52:38.766 3094-3267/? E/amsglsc: java.net.ConnectException: Connection refused
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:334)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:196)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:356)
        at java.net.Socket.connect(Socket.java:592)
        at com.android.okhttp.internal.Platform.connectSocket(Platform.java:113)
        at com.android.okhttp.Connection.connectSocket(Connection.java:196)
        at com.android.okhttp.Connection.connect(Connection.java:172)
        at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:367)
        at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:130)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:329)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:246)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:457)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:126)
        at com.amap.b.a.c.a.d.h(AndroidHttpConnectionFactory.java:148)
        at com.amap.b.a.c.a.d.d(AndroidHttpConnectionFactory.java:192)
        at com.amap.b.a.b.d.run(AsyncHttpRequestFactory.java:333)
        at com.amap.b.a.b.c.b(AsyncHttpRequestFactory.java:79)
        at com.amap.b.a.b.c.run(AsyncHttpRequestFactory.java:111)
        at com.amap.b.a.d.b.run(BaseThreadFactory.java:44)

**Comment by cuzhu** [comment]
网络自身的问题
