### ISSUE TITLE
在8.0的手机上，开启悬浮窗调试会出现Crash

### ISSUE THREAD

**Issue by dahaidadavid** [Qihoo360/ArgusAPM#29]
java.lang.RuntimeException: Unable to instantiate application com.argusapm.sample.ArgusAPMApplication: android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@1973eda -- permission denied for window type 2038
        at android.app.LoadedApk.makeApplication(LoadedApk.java:978)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5853)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1688)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:171)
        at android.app.ActivityThread.main(ActivityThread.java:6699)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:246)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
     Caused by: android.view.WindowManager$BadTokenException: Unable to add window android.view.ViewRootImpl$W@1973eda -- permission denied for window type 2038
        at android.view.ViewRootImpl.setView(ViewRootImpl.java:813)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:356)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:93)
        at com.argusapm.android.debug.view.FloatWindowManager.showBigWindow(FloatWindowManager.java:126)
        at com.argusapm.android.debug.AnalyzeManager.setShowFloatWin(AnalyzeManager.java:62)
        at com.argusapm.android.api.Client.isDebugOpen(Client.java:78)
        at com.argusapm.sample.ArgusAPMApplication.attachBaseContext(ArgusAPMApplication.java:43)
        at android.app.Application.attach(Application.java:194)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1103)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1087)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:972)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5853) 
        at android.app.ActivityThread.-wrap1(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1688) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:171) 
        at android.app.ActivityThread.main(ActivityThread.java:6699) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:246) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)

**Comment by akathink** [comment]
目前，需要自己提前申请悬浮窗权限才可以，后期我们会优化Debug模式。 @dahaidadavid
