### ISSUE TITLE
使用ASM插件，报找不到com.argusapm.android.core.job.func.FuncTrace

### ISSUE THREAD

**Issue by guanbo123456** [Qihoo360/ArgusAPM#39]
使用ASM插件，报找不到com.argusapm.android.core.job.func.FuncTrace

java.lang.NoClassDefFoundError: Failed resolution of: Lcom/argusapm/android/core/job/func/FuncTrace;
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.argusapm.android.core.job.func.FuncTrace" on path: DexPathList[[zip file "/data/app/com.yqxue.yqxue-1/base.apk"],nativeLibraryDirectories=[/data/app/com.yqxue.yqxue-1/lib/arm, /data/app/com.yqxue.yqxue-1/base.apk!/lib/armeabi, /system/lib, /vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at cn.jiguang.a.a.c.f.run(Unknown Source) 
2019-04-18 17:51:16.710 21954-22089/? E/AndroidRuntime: FATAL EXCEPTION: Thread-20
    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/argusapm/android/core/job/func/FuncTrace;
        at cn.jiguang.a.a.c.f.run(Unknown Source)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.argusapm.android.core.job.func.FuncTrace" on path: DexPathList[[zip file "/data/app/com.yqxue.yqxue-1/base.apk"],nativeLibraryDirectories=[/data/app/com.yqxue.yqxue-1/lib/arm, /data/app/com.yqxue.yqxue-1/base.apk!/lib/armeabi, /system/lib, /vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)

**Comment by akathink** [comment]
@guanbo123456 关于该问题请确认一下：
1. app的方法数是否超过了65536；
2. 采用官方提供的Demo，切换成asm插件，看看是否还有该问题。

**Comment by guanbo123456** [comment]
应该是由于开源的argus-apm-main模块代码里没有com.argusapm.android.core.job.func.FuncTrace相关文件

**Comment by akathink** [comment]
> 应该是由于开源的argus-apm-main模块代码里没有com.argusapm.android.core.job.func.FuncTrace相关文件

@guanbo123456 

HI，我在Demo里面使用        classpath 'com.qihoo360.argusapm:argus-apm-gradle-asm:3.0.1.1001' 跑了一下，没有出现上面的问题，你可以使用这个版本的插件试一下。如有问题的话，可以给我们提供一个Demo，谢谢！
