### ISSUE TITLE
编译过程 ABORT java.lang.ClassCastException

### ISSUE THREAD

**Issue by NoobEagle** [Qihoo360/ArgusAPM#6]
有看到ajcore里面的日志：
---- Compiler Messages ---
abort ABORT -- (ClassCastException) org.aspectj.apache.bcel.classfile.ConstantNameAndType cannot be cast to org.aspectj.apache.bcel.classfile.ConstantUtf8
org.aspectj.apache.bcel.classfile.ConstantNameAndType cannot be cast to org.aspectj.apache.bcel.classfile.ConstantUtf8
java.lang.ClassCastException: org.aspectj.apache.bcel.classfile.ConstantNameAndType cannot be cast to org.aspectj.apache.bcel.classfile.ConstantUtf8
	at org.aspectj.apache.bcel.classfile.ConstantPool.getConstantUtf8(ConstantPool.java:276)
	at org.aspectj.weaver.bcel.BcelConstantPoolReader.readUtf8(BcelConstantPoolReader.java:31)
	at org.aspectj.weaver.VersionedDataInputStream.readUtf8(VersionedDataInputStream.java:61)
	at org.aspectj.weaver.ResolvedMemberImpl.readResolvedMember(ResolvedMemberImpl.java:521)
	at org.aspectj.weaver.AjAttribute$EffectiveSignatureAttribute.read(AjAttribute.java:734)
	at org.aspectj.weaver.AjAttribute.read(AjAttribute.java:127)
	at org.aspectj.weaver.bcel.Utility.readAjAttributes(Utility.java:101)
	at org.aspectj.weaver.bcel.BcelMethod.unpackAjAttributes(BcelMethod.java:198)
	at org.aspectj.weaver.bcel.BcelMethod.<init>(BcelMethod.java:91)
	at org.aspectj.weaver.bcel.BcelObjectType.getDeclaredMethods(BcelObjectType.java:291)
	at org.aspectj.weaver.ReferenceType.getDeclaredMethods(ReferenceType.java:864)
	at org.aspectj.weaver.ResolvedType.getDeclaredAdvice(ResolvedType.java:977)
	at org.aspectj.weaver.ResolvedType.getDeclaredShadowMungers(ResolvedType.java:1017)
	at org.aspectj.weaver.ResolvedType.collectShadowMungers(ResolvedType.java:843)
	at org.aspectj.weaver.ResolvedType.collectCrosscuttingMembers(ResolvedType.java:770)
	at org.aspectj.weaver.CrosscuttingMembersSet.addOrReplaceAspect(CrosscuttingMembersSet.java:113)
	at org.aspectj.weaver.CrosscuttingMembersSet.addOrReplaceAspect(CrosscuttingMembersSet.java:68)
	at org.aspectj.weaver.bcel.BcelWeaver.addLibraryJarFile(BcelWeaver.java:239)
	at org.aspectj.ajdt.internal.core.builder.AjBuildManager.initBcelWorld(AjBuildManager.java:878)
	at org.aspectj.ajdt.internal.core.builder.AjBuildManager.performBuild(AjBuildManager.java:251)
	at org.aspectj.ajdt.internal.core.builder.AjBuildManager.batchBuild(AjBuildManager.java:187)
	at org.aspectj.ajdt.ajc.AjdtCommand.doCommand(AjdtCommand.java:112)
	at org.aspectj.ajdt.ajc.AjdtCommand.runCommand(AjdtCommand.java:60)
	at org.aspectj.tools.ajc.Main.run(Main.java:371)
	at com.argusapm.gradle.internal.ajc.AjcWeaver.call(AjcWeaver.kt:76)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by longxf** [comment]
Is it finally solved?
